version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
      
    steps:
      - checkout
      
      - run:  bundle install
      - run:  bundle exec jekyll build
        
      - run:
        name    : Print the current Time
        command : date
        
